version: "3"
services:
  api:
    build: ./backend
    ports:
      - "3080:3080"
    container_name: dashboard-server
  client:
    build: ./app
    ports:
      - "3000:80"
    container_name: dashboard-client