version: "3"
services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: dashboard-server
  client:
    build: ./app
    ports:
      - "80:80"
    container_name: dashboard-client